# Development environment setup

- name: Linux Desktop | Dev | Install Yarn key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Linux Desktop | Dev | Install Yarn repository
  file:
    path: /etc/apt/sources.list.d/yarn.list
    owner: root
    mode: 0644
    state: touch

- name: Linux Desktop | Dev | Install Yarn repository
  lineinfile:
    dest: /etc/apt/sources.list.d/yarn.list
    regexp: "deb http://dl.yarnpkg.com/debian/ stable main"
    line: "deb http://dl.yarnpkg.com/debian/ stable main"
    state: present

- name: Linux Desktop | Dev | Update apt cache
  apt:
    update_cache: yes

- name: Linux Desktop | Dev | Install the desktop environment for programming
  apt:
    state: present
    name: 
      - yarn
      - git
      - tig
      - openjdk-8-jdk
      - maven
      - python3
      - python3-pip
      - bpython3
      - zeal

- name: Linux Desktop | Dev | Install SpacEmacs
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: ~/.emacs.d/
    update: yes
    clone: no
    accept_hostkey: yes

- name: Linux Desktop | Dev | Configure git
  block:
    - git_config:
        name: core.excludefiles
        scope: global
        value: "~/.global-gitignore"
    - git_config:
        name: pack.windowMemory
        scope: global
        value: "100m"
    - git_config:
        name: pack.packetSizeLimit
        scope: global
        value: "512m"
    - git_config:
        name: pack.threads
        scope: global
        value: "1"
    - git_config:
        name: rebase.autosquash
        scope: global
        value: "true"

- name: Linux Desktop | Dev | Configure git to use GPG
  block:
    - git_config:
        name: commit.gpgsign
        scope: global
        value: "true"
    - git_config:
        name: user.signingkey
        scope: global
        value: "{{ gpg_hash }}"
  when: gpg is defined
